version: '3.7'

services:
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    container_name: oney-nginx
    volumes:
      - my-app:/var/www/html
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
    networks:
      - oney

  nginx-py:
    build:
      context: ..
      dockerfile: docker/nginx-py/Dockerfile
    container_name: oney-nginx-py
    volumes:
      - my-py:/var/www/html
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - python
    networks:
      - oney-py

  php:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    container_name: oney-app
    ports:
      - 9000:9000
    expose:
      - 9000
    volumes:
      - my-app:/var/www/html
    depends_on:
      - mysql
      - python
    networks:
      - oney

  mysql:
    image: mysql:5.7
    restart: always
    container_name: oney-mysql
    environment:
      MYSQL_DATABASE: 'oney_trust'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - oney

  python:
    build:
      context: ..
      dockerfile: docker/python/Dockerfile
    container_name: oney-python
    ports:
      - 8088:8088
    expose:
      - 8088
    volumes:
      - my-py:/var/www/html
    networks:
      - oney-py

networks:
  oney:
    driver: "bridge"
  oney-py:
    driver: "bridge"
volumes:
  my-db:
  my-app:
  my-py: